/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ppdai.das.service;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2020-12-30")
public class TxBeginRequest implements org.apache.thrift.TBase<TxBeginRequest, TxBeginRequest._Fields>, java.io.Serializable, Cloneable, Comparable<TxBeginRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TxBeginRequest");

  private static final org.apache.thrift.protocol.TField TX_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("txName", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TxBeginRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TxBeginRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String txName; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TX_NAME((short)1, "txName");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TX_NAME
          return TX_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TX_NAME, new org.apache.thrift.meta_data.FieldMetaData("txName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TxBeginRequest.class, metaDataMap);
  }

  public TxBeginRequest() {
  }

  public TxBeginRequest(
    java.lang.String txName)
  {
    this();
    this.txName = txName;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TxBeginRequest(TxBeginRequest other) {
    if (other.isSetTxName()) {
      this.txName = other.txName;
    }
  }

  public TxBeginRequest deepCopy() {
    return new TxBeginRequest(this);
  }

  @Override
  public void clear() {
    this.txName = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTxName() {
    return this.txName;
  }

  public TxBeginRequest setTxName(@org.apache.thrift.annotation.Nullable java.lang.String txName) {
    this.txName = txName;
    return this;
  }

  public void unsetTxName() {
    this.txName = null;
  }

  /** Returns true if field txName is set (has been assigned a value) and false otherwise */
  public boolean isSetTxName() {
    return this.txName != null;
  }

  public void setTxNameIsSet(boolean value) {
    if (!value) {
      this.txName = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TX_NAME:
      if (value == null) {
        unsetTxName();
      } else {
        setTxName((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TX_NAME:
      return getTxName();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TX_NAME:
      return isSetTxName();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TxBeginRequest)
      return this.equals((TxBeginRequest)that);
    return false;
  }

  public boolean equals(TxBeginRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_txName = true && this.isSetTxName();
    boolean that_present_txName = true && that.isSetTxName();
    if (this_present_txName || that_present_txName) {
      if (!(this_present_txName && that_present_txName))
        return false;
      if (!this.txName.equals(that.txName))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetTxName()) ? 131071 : 524287);
    if (isSetTxName())
      hashCode = hashCode * 8191 + txName.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TxBeginRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetTxName()).compareTo(other.isSetTxName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTxName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.txName, other.txName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TxBeginRequest(");
    boolean first = true;

    sb.append("txName:");
    if (this.txName == null) {
      sb.append("null");
    } else {
      sb.append(this.txName);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (txName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'txName' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TxBeginRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TxBeginRequestStandardScheme getScheme() {
      return new TxBeginRequestStandardScheme();
    }
  }

  private static class TxBeginRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<TxBeginRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TxBeginRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TX_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.txName = iprot.readString();
              struct.setTxNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TxBeginRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.txName != null) {
        oprot.writeFieldBegin(TX_NAME_FIELD_DESC);
        oprot.writeString(struct.txName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TxBeginRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TxBeginRequestTupleScheme getScheme() {
      return new TxBeginRequestTupleScheme();
    }
  }

  private static class TxBeginRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<TxBeginRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TxBeginRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.txName);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TxBeginRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.txName = iprot.readString();
      struct.setTxNameIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

